<%@ Page Title="" Language="C#" MasterPageFile="~/USERFILE/User.Master" AutoEventWireup="true" CodeBehind="BookingInfo.aspx.cs" Inherits="TRIPMANAGEMENYSYSTEM.USERFILE.BookingInfo" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <center><h1>  Your Upcoming Booked Tours</h1><br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="true" DataKeyNames="TOUR_ID" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="TOUR_ID" HeaderText="TOUR ID" InsertVisible="False" ReadOnly="True" SortExpression="TOUR_ID" />
                <asp:BoundField DataField="TOUR_NAME" HeaderText="TOUR NAME" SortExpression="TOUR_NAME" />
                <asp:BoundField DataField="FirstName" HeaderText="NAME" SortExpression="FirstName" />
                <asp:BoundField DataField="Email" HeaderText="EMAIL" SortExpression="Email" />
                <asp:BoundField DataField="PLACE" HeaderText="PLACE" SortExpression="PLACE" />

            </Columns>
            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
               <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
               <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
               <RowStyle BackColor="White" ForeColor="#330099" />
               <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
               <SortedAscendingCellStyle BackColor="#FEFCEB" />
               <SortedAscendingHeaderStyle BackColor="#AF0101" />
               <SortedDescendingCellStyle BackColor="#F6F0C0" />
               <SortedDescendingHeaderStyle BackColor="#7E0000" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:tourdbConnectionString8 %>" DeleteCommand="Delete from [booking] Where [TOUR_ID]=@TOUR_ID" SelectCommand="SELECT * FROM [booking]" >
          
        </asp:SqlDataSource>
</center>
</asp:Content>
